### ISSUE TITLE
Review/Approval workflow

### ISSUE THREAD

**Issue by lfrancke** [MaibornWolff/SecObserve#1276]
As a user of SecObserve I'd like to make sure to only publish well written and thoroughly reviewed vulnerability assessments. Therefore I'd like to have a kind of review/approval workflow where each assessment has to be reviewed by X amount of people before it is finally published.

This is to protect against various scenarios:
- Accidents (I accidentally clicked the wrong button)
- Malicious attempts ("I just need to get to 0, I'll just dismiss all of these")
- Oversights/Errors ("Someone needs to cross-check/sanitize my assessment")

This can (and probably should) be an optional thing and I'm not entirely sure what the final workflow should look like but I'm fully convinced that this is something that will be mandatory going forward as a wrong assessment can lead to liabilities and financial loss for a company as well as extra work for all downstream users.

Reviews don't give a 100% protection but they are industry best practice everywhere else (code reviews) and I think we should apply the same good principles here.

_Note_: This issue is meant as a discussion starter and not fully fleshed out yet.

**Comment by StefanFl** [comment]
My current idea:

* The ObservationLog gets a new status flag, which can be `Approved`, `in Review` or `Rejected` plus a new field `review_comment`
* The Product gets a new boolean flag `assessments_need_review`
* If `assessments_need_review` is set, the status of a new manual assessment will be `in Review`. Someone needs to either approve or reject it. If `assessment_needs_review` is false, a new manual assessment will get the status `Approved` automatically.
* The result of the assessment (observation.status or observation.severity) will only be used, if the assessment has been approved. 
* The Product will get a new `Review` tab in the UI, with a list of assessments that need a review or have been rejected.

Currently not sure who can review assessments, maybe Maintainers and Owners.

**Comment by StefanFl** [comment]
As a bonus we could solve https://github.com/MaibornWolff/SecObserve/discussions/1106#discussioncomment-8530772 as well:

* The product gets another boolean flag `new_observations_in_review` 
* If it is set, than new observations get the status `in Review` instead of open.
* The observations with the status `in Review` would be shown in the new `Review` tab as well. 

This would fit to https://www.cisa.gov/sites/default/files/2023-11/When-to-Issue-a-VEX-508c.pdf which states:

> Ideally, when a new vulnerability is disclosed, an “under_investigation” status should be issued. When the investigation has concluded, status should be updated, for example, noting that the product is “affected” or “not_affected.”

**Comment by lfrancke** [comment]
I like the idea in general.
As to who gets to do the review I have not really thought about it yet and I also did not look at the authorization model of SecObserve in general yet.

[GitHub](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews) says:

> If your repository requires reviews, pull requests must have a specific number of approving reviews from people with write or admin permissions in the repository before they can be merged.

I think we can probably live with requiring a single review for now but it might be worth future proofing this by allowing for a future with more than one required reviewer. This might be overkill as well though right now.

**Comment by StefanFl** [comment]
There is an implementation merged to the dev branch, see https://github.com/MaibornWolff/SecObserve/blob/dev/docs/usage/assess_observations.md for how to use it.

**Comment by lfrancke** [comment]
Wow! That was incredibly fast. Thank you. We'll check it out soon!

**Comment by StefanFl** [comment]
Comment https://github.com/MaibornWolff/SecObserve/issues/1276#issuecomment-2012821276 will be solved with issue #1312

**Comment by StefanFl** [comment]
Released with [1.10.0](https://github.com/MaibornWolff/SecObserve/releases/tag/v1.10.0)
