### ISSUE TITLE
Add a robots.txt

### ISSUE THREAD

**Issue by lfrancke** [MaibornWolff/SecObserve#1302]
I just googled for SecObserve and one of the first results is a hosted SecObserve instance that got crawled somehow.

I don't think it's intended for the public and as such would love an option of rolling out a robots.txt automatically.

**Comment by StefanFl** [comment]
Well spotted, thanks a lot @lfrancke

**Comment by StefanFl** [comment]
It's not an option now, but there is a `robots.txt` for both backend and frontend like this:

```
User-agent: *
Disallow: /
```

**Comment by lfrancke** [comment]
Shall we close this issue or do you want to keep it open?

**Comment by StefanFl** [comment]
I will do it when it is released

**Comment by StefanFl** [comment]
Released with [1.10.0](https://github.com/MaibornWolff/SecObserve/releases/tag/v1.10.0)
