### ISSUE TITLE
Review/Approval workflow with respect to rules

### ISSUE THREAD

**Issue by dervoeti** [MaibornWolff/SecObserve#1449]
Related to https://github.com/MaibornWolff/SecObserve/issues/1276

As a reviewer, I can't directly make assessments about vulnerabilities if "Assessments need approval" is enabled.

What I *can* do is create a general or product specific rule that does that assessment for me. Then the next time this vulnerability is reported to SecObserve (which happens daily in our case, since we do daily scans) the assessment is auto-approved.

I think possible solutions are either disabling auto-approval for rules or implementing a review process for rules.

**Comment by StefanFl** [comment]
This is really a loop hole that needs to be fixed

**Comment by StefanFl** [comment]
I tend to implement a review process for rules. Otherwise users might get a lot of reviews for observations.

**Comment by StefanFl** [comment]
released with 1.13.0

**Comment by dervoeti** [comment]
Just tested this, awesome, thanks a lot!
