### ISSUE TITLE
Assessment not saved in observation log if only a comment is added

### ISSUE THREAD

**Issue by dervoeti** [MaibornWolff/SecObserve#1541]
If you're viewing an observation and click on "assessment", don't change anything and just add a comment, a success message "Observation updated" is presented but the comment is not saved.

I briefly looked at the code, the most relevant part should be the `save_assessment` function in `backend/application/core/services/assessment.py`.

This function should either always create an entry in the observation log or return a success indicator, which is then presented to the user in the UI.

TBD if an assessment with just a comment and no other change is considered a valid assessment.
If not, an error should be presented. If it is valid, it should be stored in the database.

**Comment by StefanFl** [comment]
Good point, @dervoeti. Would you expect the assessment needs an approval if neither status or severity has been changed? I personally would just write the comment without the need for an approval.

**Comment by dervoeti** [comment]
Yeah I'd agree that just a comment doesn't need to be approved. As far as I know these comments are SecObserve internal anyway and don't get published in VEX statements.

**Comment by StefanFl** [comment]
published with release 1.14.0
