### ISSUE TITLE
Linear Integration

### ISSUE THREAD

**Issue by y0anfa** [MaibornWolff/SecObserve#1772]
Hi,

My organization uses Linear for issue tracking & project management. Is an integration with this tool planned in the future?
We are considering using SecObserve internally and such an integration would be very helpful, and therefore we could consider contributing to the project.

Thanks!

**Comment by StefanFl** [comment]
Hi @y0anfa, I personally don't plan to write an integration with Linear. But if you want to contribute to the project with such an integration, that would be great.

**Comment by StefanFl** [comment]
Closed due to inactivity
