### ISSUE TITLE
Specifying multiple values in CORS_ALLOWED_ORIGINS

### ISSUE THREAD

**Issue by bo0ts** [MaibornWolff/SecObserve#2307]
How to specify multiple values in `CORS_ALLOWED_ORIGINS` environment variable? 

I've tried several things but all lead to different `corsheaders.E014`.

**Comment by StefanFl** [comment]
Hi @bo0ts, it wasn't possible up to now. With PR #2313 you can specify a comma-separated list for `CORS_ALLOWED_ORIGINS`. It is scheduled to be released next week.
