### ISSUE TITLE
Swagger UI does not load

### ISSUE THREAD

**Issue by bo0ts** [MaibornWolff/SecObserve#2320]
When trying to load the swagger-ui at `api/oa3/swagger-ui` a recent Chrome and Firefox both fail on similar errors:

```
The resource from “https://secobserve.mydomain.intern/django-static/drf_spectacular_sidecar/swagger-ui-dist/swagger-ui.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
The resource from “https://secobserve.mydomain.intern/django-static/drf_spectacular_sidecar/swagger-ui-dist/swagger-ui-bundle.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
The resource from “https://secobserve.mydomain.intern/django-static/drf_spectacular_sidecar/swagger-ui-dist/swagger-ui-standalone-preset.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
Loading failed for the <script> with source “https://secobserve.mydomain.intern/django-static/drf_spectacular_sidecar/swagger-ui-dist/swagger-ui-bundle.js”. swagger-ui:20:95
The resource from “https://secobserve.mydomain.intern/django-static/drf_spectacular_sidecar/swagger-ui-dist/swagger-ui-standalone-preset.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
Loading failed for the <script> with source “https://secobserve.mydomain.intern/django-static/drf_spectacular_sidecar/swagger-ui-dist/swagger-ui-standalone-preset.js”. swagger-ui:21:106
Uncaught ReferenceError: SwaggerUIBundle is not defined
    <anonymous> https://secobserve.mydomain.intern/api/oa3/swagger-ui?script=:117
```

**Comment by StefanFl** [comment]
I checked it with  a development version and a productive version (1.22.5) with both Firefox and Chrome and cannot reproduce it. The Swagger UI is loaded and all the MIME types are correct, e.g. `text/css; charset="utf-8"`for `https://secobserve-backend.example.com/django-static/drf_spectacular_sidecar/swagger-ui-dist/swagger-ui.css`.

Is it possible something on your server changes the MIME types?

**Comment by bo0ts** [comment]
No, there isn't. This is the response I get directly from the `secobserve-frontend` container without going through any other infrastructure:

```
curl -s -I localhost:3000/django-static/drf_spectacular_sidecar/swagger-ui-dist/swagger-ui.css
HTTP/1.1 200 OK
Server: nginx
Date: Fri, 06 Dec 2024 13:41:50 GMT
Content-Type: text/html
Content-Length: 7596
...
```

**Comment by StefanFl** [comment]
You have to use the URL of the backend, not the frontend, to get the Swagger UI.

Nevertheless weird one gets a 200 using the frontend url, it should be a 404. But I get the 200 as well.

**Comment by bo0ts** [comment]
OK, that explains it. I'm using path-based routing to serve backend and frontend from the same domain and only routed the `/api` path to the backend. Thanks for your help. I'll leave this open for the investigation why that path actually works in the frontend.

**Comment by StefanFl** [comment]
It seems to be a feature of using React HashRouter. It could be changed through the nginx configuration, but that might cause other problems, so we will accept it for the moment.
