### ISSUE TITLE
Suggestion: Add creation of CSAF VEX to distribute information about "irrelevant results"

### ISSUE THREAD

**Issue by tschmidtb51** [MaibornWolff/SecObserve#747]
The README says:

> With the help of automatically executed rules and manual assessments, the results can be efficiently evaluated to eliminate irrelevant results and accept risks. This allows the development team to concentrate on fixing the relevant vulnerabilities.

As we already have the information from manual assessments, what about creating CSAF VEX from them?

**Comment by StefanFl** [comment]
Hi @tschmidtb51, that's a good idea, thank you for that. A lot of information is already in SecObserve, but some would still be missing:

* A lot of data for the `document` section, which might be configured statically.
* The `product_tree` section should be not too bad, a `product_id` is missing and I have to check the relationships.
* The `vulnerabilities` will need some work. First to be able to fulfil the meaning of all attributes of the CSAF specification and second an editorial function, maybe an entity decides not to disclose all observations.

I will put the CSAF VEX in the backlog, but it might need some time. 

Do you by any chance know, if the EU Cyber Resiliance Act defines, how vendors have to report vulnerabilities? Will it be CSAF based?

**Comment by tschmidtb51** [comment]
@StefanFl If you need more input: BSI is offering a series of CSAF workshops: https://www.allianz-fuer-cybersicherheit.de/Webs/ACS/DE/Netzwerk-Formate/Veranstaltungen-und-Austausch/CSAFversum/CSAF_english.html

> Do you by any chance know, if the EU Cyber Resiliance Act defines, how vendors have to report vulnerabilities? Will it be CSAF based?

BSI is not directly involved in writing the CRA. Based on my knowledge, the CRA will not call out specific standards as this will be done through harmonized norms. IMHO, CSAF seems to be the obvious choice given that you have to provide information on the vulnerability and its remediation (=> security advisory).

**Comment by StefanFl** [comment]
Design and implementation have started:

* https://github.com/MaibornWolff/SecObserve/discussions/1106
* https://github.com/MaibornWolff/SecObserve/pull/1125

But it will be a long way.

**Comment by StefanFl** [comment]
Draft PR: https://github.com/MaibornWolff/SecObserve/pull/1146

**Comment by StefanFl** [comment]
An experimental implementation for CSAF and OpenVex will be part of the next release.
